/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { CarteDeTransport } from "./CarteDeTransport";
import { CarteDeTransportCountArgs } from "./CarteDeTransportCountArgs";
import { CarteDeTransportFindManyArgs } from "./CarteDeTransportFindManyArgs";
import { CarteDeTransportFindUniqueArgs } from "./CarteDeTransportFindUniqueArgs";
import { DeleteCarteDeTransportArgs } from "./DeleteCarteDeTransportArgs";
import { CarteDeTransportService } from "../carteDeTransport.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => CarteDeTransport)
export class CarteDeTransportResolverBase {
  constructor(
    protected readonly service: CarteDeTransportService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "CarteDeTransport",
    action: "read",
    possession: "any",
  })
  async _carteDeTransportsMeta(
    @graphql.Args() args: CarteDeTransportCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [CarteDeTransport])
  @nestAccessControl.UseRoles({
    resource: "CarteDeTransport",
    action: "read",
    possession: "any",
  })
  async carteDeTransports(
    @graphql.Args() args: CarteDeTransportFindManyArgs
  ): Promise<CarteDeTransport[]> {
    return this.service.carteDeTransports(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => CarteDeTransport, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "CarteDeTransport",
    action: "read",
    possession: "own",
  })
  async carteDeTransport(
    @graphql.Args() args: CarteDeTransportFindUniqueArgs
  ): Promise<CarteDeTransport | null> {
    const result = await this.service.carteDeTransport(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => CarteDeTransport)
  @nestAccessControl.UseRoles({
    resource: "CarteDeTransport",
    action: "delete",
    possession: "any",
  })
  async deleteCarteDeTransport(
    @graphql.Args() args: DeleteCarteDeTransportArgs
  ): Promise<CarteDeTransport | null> {
    try {
      return await this.service.deleteCarteDeTransport(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
