/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import {
  Prisma,
  VehicleMaintenance as PrismaVehicleMaintenance,
} from "@prisma/client";

export class VehicleMaintenanceServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.VehicleMaintenanceCountArgs, "select">
  ): Promise<number> {
    return this.prisma.vehicleMaintenance.count(args);
  }

  async vehicleMaintenances<T extends Prisma.VehicleMaintenanceFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.VehicleMaintenanceFindManyArgs>
  ): Promise<PrismaVehicleMaintenance[]> {
    return this.prisma.vehicleMaintenance.findMany<Prisma.VehicleMaintenanceFindManyArgs>(
      args
    );
  }
  async vehicleMaintenance<T extends Prisma.VehicleMaintenanceFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.VehicleMaintenanceFindUniqueArgs>
  ): Promise<PrismaVehicleMaintenance | null> {
    return this.prisma.vehicleMaintenance.findUnique(args);
  }
  async createVehicleMaintenance<T extends Prisma.VehicleMaintenanceCreateArgs>(
    args: Prisma.SelectSubset<T, Prisma.VehicleMaintenanceCreateArgs>
  ): Promise<PrismaVehicleMaintenance> {
    return this.prisma.vehicleMaintenance.create<T>(args);
  }
  async updateVehicleMaintenance<T extends Prisma.VehicleMaintenanceUpdateArgs>(
    args: Prisma.SelectSubset<T, Prisma.VehicleMaintenanceUpdateArgs>
  ): Promise<PrismaVehicleMaintenance> {
    return this.prisma.vehicleMaintenance.update<T>(args);
  }
  async deleteVehicleMaintenance<T extends Prisma.VehicleMaintenanceDeleteArgs>(
    args: Prisma.SelectSubset<T, Prisma.VehicleMaintenanceDeleteArgs>
  ): Promise<PrismaVehicleMaintenance> {
    return this.prisma.vehicleMaintenance.delete(args);
  }
}
