/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { VehicleMaintenanceService } from "../vehicleMaintenance.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { VehicleMaintenanceCreateInput } from "./VehicleMaintenanceCreateInput";
import { VehicleMaintenance } from "./VehicleMaintenance";
import { VehicleMaintenanceFindManyArgs } from "./VehicleMaintenanceFindManyArgs";
import { VehicleMaintenanceWhereUniqueInput } from "./VehicleMaintenanceWhereUniqueInput";
import { VehicleMaintenanceUpdateInput } from "./VehicleMaintenanceUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class VehicleMaintenanceControllerBase {
  constructor(
    protected readonly service: VehicleMaintenanceService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: VehicleMaintenance })
  @nestAccessControl.UseRoles({
    resource: "VehicleMaintenance",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createVehicleMaintenance(
    @common.Body() data: VehicleMaintenanceCreateInput
  ): Promise<VehicleMaintenance> {
    return await this.service.createVehicleMaintenance({
      data: data,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [VehicleMaintenance] })
  @ApiNestedQuery(VehicleMaintenanceFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "VehicleMaintenance",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async vehicleMaintenances(
    @common.Req() request: Request
  ): Promise<VehicleMaintenance[]> {
    const args = plainToClass(VehicleMaintenanceFindManyArgs, request.query);
    return this.service.vehicleMaintenances({
      ...args,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: VehicleMaintenance })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "VehicleMaintenance",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async vehicleMaintenance(
    @common.Param() params: VehicleMaintenanceWhereUniqueInput
  ): Promise<VehicleMaintenance | null> {
    const result = await this.service.vehicleMaintenance({
      where: params,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: VehicleMaintenance })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "VehicleMaintenance",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateVehicleMaintenance(
    @common.Param() params: VehicleMaintenanceWhereUniqueInput,
    @common.Body() data: VehicleMaintenanceUpdateInput
  ): Promise<VehicleMaintenance | null> {
    try {
      return await this.service.updateVehicleMaintenance({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: VehicleMaintenance })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "VehicleMaintenance",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteVehicleMaintenance(
    @common.Param() params: VehicleMaintenanceWhereUniqueInput
  ): Promise<VehicleMaintenance | null> {
    try {
      return await this.service.deleteVehicleMaintenance({
        where: params,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
