/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { UserLog } from "./UserLog";
import { UserLogCountArgs } from "./UserLogCountArgs";
import { UserLogFindManyArgs } from "./UserLogFindManyArgs";
import { UserLogFindUniqueArgs } from "./UserLogFindUniqueArgs";
import { DeleteUserLogArgs } from "./DeleteUserLogArgs";
import { UserLogService } from "../userLog.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => UserLog)
export class UserLogResolverBase {
  constructor(
    protected readonly service: UserLogService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "UserLog",
    action: "read",
    possession: "any",
  })
  async _userLogsMeta(
    @graphql.Args() args: UserLogCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [UserLog])
  @nestAccessControl.UseRoles({
    resource: "UserLog",
    action: "read",
    possession: "any",
  })
  async userLogs(
    @graphql.Args() args: UserLogFindManyArgs
  ): Promise<UserLog[]> {
    return this.service.userLogs(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => UserLog, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "UserLog",
    action: "read",
    possession: "own",
  })
  async userLog(
    @graphql.Args() args: UserLogFindUniqueArgs
  ): Promise<UserLog | null> {
    const result = await this.service.userLog(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => UserLog)
  @nestAccessControl.UseRoles({
    resource: "UserLog",
    action: "delete",
    possession: "any",
  })
  async deleteUserLog(
    @graphql.Args() args: DeleteUserLogArgs
  ): Promise<UserLog | null> {
    try {
      return await this.service.deleteUserLog(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
