/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { Administrateur } from "./Administrateur";
import { AdministrateurCountArgs } from "./AdministrateurCountArgs";
import { AdministrateurFindManyArgs } from "./AdministrateurFindManyArgs";
import { AdministrateurFindUniqueArgs } from "./AdministrateurFindUniqueArgs";
import { DeleteAdministrateurArgs } from "./DeleteAdministrateurArgs";
import { AdministrateurService } from "../administrateur.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Administrateur)
export class AdministrateurResolverBase {
  constructor(
    protected readonly service: AdministrateurService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Administrateur",
    action: "read",
    possession: "any",
  })
  async _administrateursMeta(
    @graphql.Args() args: AdministrateurCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Administrateur])
  @nestAccessControl.UseRoles({
    resource: "Administrateur",
    action: "read",
    possession: "any",
  })
  async administrateurs(
    @graphql.Args() args: AdministrateurFindManyArgs
  ): Promise<Administrateur[]> {
    return this.service.administrateurs(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Administrateur, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Administrateur",
    action: "read",
    possession: "own",
  })
  async administrateur(
    @graphql.Args() args: AdministrateurFindUniqueArgs
  ): Promise<Administrateur | null> {
    const result = await this.service.administrateur(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Administrateur)
  @nestAccessControl.UseRoles({
    resource: "Administrateur",
    action: "delete",
    possession: "any",
  })
  async deleteAdministrateur(
    @graphql.Args() args: DeleteAdministrateurArgs
  ): Promise<Administrateur | null> {
    try {
      return await this.service.deleteAdministrateur(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
